server:
  port: 8091
#  随机端口
#  port: ${random.int[8080,9999]}
spring:
  application:
    name: demo
  # mysql configuration
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    schema-username: root
    schema-password: root
    platform: mysql
    continue-on-error: true
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver


# mybatis configuration
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.yx.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

myTest: hi

logging:
  config:
  level:
    com.yx.demo: trace
#  path: C:/Users/yangxiao/Desktop   #默认生成 spring.log
#  file: C:/Users/yangxiao/Desktop/demo.log   #指定文件名