server:
  port: 8090
spring:
  application:
    name: auth
# mysql configuration
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema-username: root
    schema-password: root
    schema:
      - classpath:sql/user.sql
    initialization-mode: always
    platform: mysql
    continue-on-error: true


  # redis configuration
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout:
    jedis:
      pool:
        max-active: 8
# mybatis configuration
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.yx.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
